services:
  _defaults:
    autowire: true
    autoconfigure: true
  Tm\OrangeMoneyBundle\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
  Tm\OrangeMoneyBundle\Http\OneStepPayService:
    public: true
