services:
  _defaults:
    autowire: true
    autoconfigure: true
  Tm\OrangeMoneyBundle\:
    resource: '../src/'
    exclude:
      - '../src/{DependencyInjection,Entity}'
  Tm\OrangeMoneyBundle\Http\Api\:
    resource: '../src/Http/Api/'
    arguments:
      $base: '%mamadou.orange_money.base%'
    public: true
